import type { GroupListItem, GroupDetail } from '@/features/groups/types'
import type { AttendanceRosterStudent, AttendanceSummary } from '@/features/attendance/types'
import type { ExamListItem, StudentExamLeaderboard } from '@/features/exams/types'
import type { PaymentRecord, FinanceStats, DebtSummary } from '@/features/finance/types'
import type { StudentListItem, StudentDetail } from '@/features/students/types'
import type { TeacherListItem } from '@/features/teachers/types'
import type { ParentListItem } from '@/features/parents/types'

// Mock Students
export const MOCK_STUDENTS: StudentListItem[] = [
  {
    id: 'std-1',
    first_name: 'Jamshid',
    last_name: 'Rasulov',
    avatar_url: null,
    phone: '+998 90 123 45 67',
    birth_date: '2008-04-12',
    gender: 'MALE',
    status: 'ACTIVE',
    notes: 'Matematika fanidan a\'lochi o\'quvchi',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    is_deleted: false,
    primary_group: { id: 'grp-1', name: 'Matematika Intensive (G-12)', subject: 'Matematika', status: 'ACTIVE' },
    primary_parent: { id: 'prn-1', first_name: 'Dilshod', last_name: 'Rasulov', phone: '+998 90 999 11 22', email: null, notification_enabled: true, telegram_verified: true },
    parent_count: 1,
    group_count: 1,
  },
  {
    id: 'std-2',
    first_name: 'Jasur',
    last_name: 'Alimov',
    avatar_url: null,
    phone: '+998 97 765 43 21',
    birth_date: '2009-07-25',
    gender: 'MALE',
    status: 'ACTIVE',
    notes: 'IELTS guruhida tahsil olmoqda',
    created_at: '2026-08-19T14:30:00Z',
    updated_at: '2026-08-19T14:30:00Z',
    is_deleted: false,
    primary_group: { id: 'grp-2', name: 'IELTS 7.5+ Masterclass', subject: 'Ingliz tili', status: 'ACTIVE' },
    primary_parent: { id: 'prn-2', first_name: 'Nilufar', last_name: 'Alimova', phone: '+998 93 555 44 33', email: null, notification_enabled: true, telegram_verified: true },
    parent_count: 1,
    group_count: 1,
  },
  {
    id: 'std-3',
    first_name: 'Madina',
    last_name: 'Karimova',
    avatar_url: null,
    phone: '+998 99 888 77 66',
    birth_date: '2010-01-15',
    gender: 'FEMALE',
    status: 'ACTIVE',
    notes: 'Frontend dasturlash kursida',
    created_at: '2026-08-15T09:00:00Z',
    updated_at: '2026-08-15T09:00:00Z',
    is_deleted: false,
    primary_group: { id: 'grp-3', name: 'Frontend React & Next.js', subject: 'Dasturlash', status: 'ACTIVE' },
    primary_parent: { id: 'prn-3', first_name: 'Shavkat', last_name: 'Karimov', phone: '+998 90 777 88 99', email: null, notification_enabled: true, telegram_verified: false },
    parent_count: 1,
    group_count: 1,
  },
  {
    id: 'std-4',
    first_name: 'Behruz',
    last_name: 'Saidov',
    avatar_url: null,
    phone: '+998 91 234 56 78',
    birth_date: '2008-11-03',
    gender: 'MALE',
    status: 'ACTIVE',
    notes: 'Fizika fanidan olimpiada tayyorgarligi',
    created_at: '2026-08-10T12:00:00Z',
    updated_at: '2026-08-10T12:00:00Z',
    is_deleted: false,
    primary_group: { id: 'grp-4', name: 'Fizika Olimpiada Guruhi', subject: 'Fizika', status: 'ACTIVE' },
    primary_parent: null,
    parent_count: 0,
    group_count: 1,
  },
  {
    id: 'std-5',
    first_name: 'Malika',
    last_name: 'Umarova',
    avatar_url: null,
    phone: '+998 93 111 22 33',
    birth_date: '2009-09-19',
    gender: 'FEMALE',
    status: 'ACTIVE',
    notes: 'Ingliz tili kursi',
    created_at: '2026-08-05T16:00:00Z',
    updated_at: '2026-08-05T16:00:00Z',
    is_deleted: false,
    primary_group: { id: 'grp-2', name: 'IELTS 7.5+ Masterclass', subject: 'Ingliz tili', status: 'ACTIVE' },
    primary_parent: null,
    parent_count: 0,
    group_count: 1,
  },
]

// Mock Groups
export const MOCK_GROUPS: GroupListItem[] = [
  {
    id: 'grp-1',
    organization_id: 'org-ilmziyo',
    name: 'Matematika Intensive (G-12)',
    subject: 'Matematika',
    teacher_id: 'tch-1',
    teacher: {
      id: 'tch-1',
      first_name: 'Anvar',
      last_name: 'Qodirov',
      phone: '+998 90 111 22 33',
      email: 'anvar@ilmziyo.uz',
      avatar_url: null,
      specialization: 'Oliy Matematika',
    },
    room: '304-xona (Sharq)',
    schedule: {
      days: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
      time: '14:00 - 15:30',
    },
    capacity: 16,
    status: 'ACTIVE',
    student_count: 14,
    created_at: '2026-08-01T08:00:00Z',
    updated_at: '2026-08-01T08:00:00Z',
    is_deleted: false,
  },
  {
    id: 'grp-2',
    organization_id: 'org-ilmziyo',
    name: 'IELTS 7.5+ Masterclass',
    subject: 'Ingliz tili',
    teacher_id: 'tch-2',
    teacher: {
      id: 'tch-2',
      first_name: 'Lola',
      last_name: 'Karimova',
      phone: '+998 97 222 33 44',
      email: 'lola@ilmziyo.uz',
      avatar_url: null,
      specialization: 'IELTS & CEFR C1',
    },
    room: "201-xona (G'arb)",
    schedule: {
      days: ['TUESDAY', 'THURSDAY', 'SATURDAY'],
      time: '16:00 - 17:30',
    },
    capacity: 14,
    status: 'ACTIVE',
    student_count: 12,
    created_at: '2026-08-02T09:00:00Z',
    updated_at: '2026-08-02T09:00:00Z',
    is_deleted: false,
  },
  {
    id: 'grp-3',
    organization_id: 'org-ilmziyo',
    name: 'Frontend React & Next.js',
    subject: 'Dasturlash',
    teacher_id: 'tch-3',
    teacher: {
      id: 'tch-3',
      first_name: 'Javohirbek',
      last_name: 'Asqarov',
      phone: '+998 90 777 00 11',
      email: 'javohir@ilmziyo.uz',
      avatar_url: null,
      specialization: 'Senior Full-Stack & AI',
    },
    room: 'Lab-1 (IT Hub)',
    schedule: {
      days: ['MONDAY', 'WEDNESDAY', 'FRIDAY'],
      time: '18:00 - 20:00',
    },
    capacity: 12,
    status: 'ACTIVE',
    student_count: 10,
    created_at: '2026-08-03T10:00:00Z',
    updated_at: '2026-08-03T10:00:00Z',
    is_deleted: false,
  },
  {
    id: 'grp-4',
    organization_id: 'org-ilmziyo',
    name: 'Fizika Olimpiada Guruhi',
    subject: 'Fizika',
    teacher_id: 'tch-1',
    teacher: {
      id: 'tch-1',
      first_name: 'Anvar',
      last_name: 'Qodirov',
      phone: '+998 90 111 22 33',
      email: 'anvar@ilmziyo.uz',
      avatar_url: null,
      specialization: 'Oliy Matematika & Fizika',
    },
    room: '302-xona',
    schedule: {
      days: ['TUESDAY', 'THURSDAY', 'SATURDAY'],
      time: '14:00 - 15:30',
    },
    capacity: 10,
    status: 'ACTIVE',
    student_count: 8,
    created_at: '2026-08-04T11:00:00Z',
    updated_at: '2026-08-04T11:00:00Z',
    is_deleted: false,
  },
]

// Mock Attendance Roster
export const MOCK_ATTENDANCE_ROSTER: AttendanceRosterStudent[] = [
  {
    student_id: 'std-1',
    student_name: 'Jamshid Rasulov',
    first_name: 'Jamshid',
    last_name: 'Rasulov',
    avatar_url: null,
    phone: '+998 90 123 45 67',
    attendance_id: 'att-1',
    status: 'PRESENT',
    note: '',
    parent_id: 'prn-1',
    parent_name: 'Dilshod Rasulov',
    parent_phone: '+998 90 999 11 22',
    telegram_verified: true,
  },
  {
    student_id: 'std-2',
    student_name: 'Jasur Alimov',
    first_name: 'Jasur',
    last_name: 'Alimov',
    avatar_url: null,
    phone: '+998 97 765 43 21',
    attendance_id: 'att-2',
    status: 'ABSENT',
    note: 'Ota-onasiga Telegram orqali ogohlantirish yuborildi',
    parent_id: 'prn-2',
    parent_name: 'Nilufar Alimova',
    parent_phone: '+998 93 555 44 33',
    telegram_verified: true,
  },
  {
    student_id: 'std-3',
    student_name: 'Madina Karimova',
    first_name: 'Madina',
    last_name: 'Karimova',
    avatar_url: null,
    phone: '+998 99 888 77 66',
    attendance_id: 'att-3',
    status: 'PRESENT',
    note: '',
    parent_id: 'prn-3',
    parent_name: 'Shavkat Karimov',
    parent_phone: '+998 90 777 88 99',
    telegram_verified: false,
  },
  {
    student_id: 'std-4',
    student_name: 'Behruz Saidov',
    first_name: 'Behruz',
    last_name: 'Saidov',
    avatar_url: null,
    phone: '+998 91 234 56 78',
    attendance_id: 'att-4',
    status: 'LATE',
    note: '10 daqiqa kechikib kirdi',
    parent_id: null,
    parent_name: null,
    parent_phone: null,
    telegram_verified: false,
  },
  {
    student_id: 'std-5',
    student_name: 'Malika Umarova',
    first_name: 'Malika',
    last_name: 'Umarova',
    avatar_url: null,
    phone: '+998 93 111 22 33',
    attendance_id: 'att-5',
    status: 'EXCUSED',
    note: "Shifokor ma'lumotnomasi bor",
    parent_id: null,
    parent_name: null,
    parent_phone: null,
    telegram_verified: false,
  },
]

// Mock Exams
export const MOCK_EXAMS: ExamListItem[] = [
  {
    id: 'ex-1',
    organization_id: 'org-ilmziyo',
    group_id: 'grp-1',
    group_name: 'Matematika Intensive (G-12)',
    teacher_id: 'tch-1',
    teacher_name: 'Anvar Qodirov',
    title: 'Hosilalar va Integrallar Blits-Imtihoni',
    subject: 'Matematika',
    exam_date: '2026-09-08',
    maximum_score: 100,
    results_count: 14,
    average_score: 84.5,
    highest_score: 98,
    created_at: '2026-09-05T10:00:00Z',
  },
  {
    id: 'ex-2',
    organization_id: 'org-ilmziyo',
    group_id: 'grp-2',
    group_name: 'IELTS 7.5+ Masterclass',
    teacher_id: 'tch-2',
    teacher_name: 'Lola Karimova',
    title: 'Full Mock Exam (Reading & Listening)',
    subject: 'Ingliz tili',
    exam_date: '2026-09-05',
    maximum_score: 100,
    results_count: 12,
    average_score: 82.0,
    highest_score: 95,
    created_at: '2026-09-02T12:00:00Z',
  },
]

// Mock Leaderboard
export const MOCK_LEADERBOARD: StudentExamLeaderboard[] = [
  {
    student_id: 'std-1',
    student_name: 'Jamshid Rasulov',
    avatar_url: null,
    score: 98,
    maximum_score: 100,
    percentage: 98,
    grade: 'A',
    rank: 1,
    badge: '🥇 1-oʼrin',
  },
  {
    student_id: 'std-3',
    student_name: 'Madina Karimova',
    avatar_url: null,
    score: 92,
    maximum_score: 100,
    percentage: 92,
    grade: 'A',
    rank: 2,
    badge: '🥈 2-oʼrin',
  },
  {
    student_id: 'std-4',
    student_name: 'Behruz Saidov',
    avatar_url: null,
    score: 86,
    maximum_score: 100,
    percentage: 86,
    grade: 'B',
    rank: 3,
    badge: '🥉 3-oʼrin',
  },
  {
    student_id: 'std-2',
    student_name: 'Jasur Alimov',
    avatar_url: null,
    score: 78,
    maximum_score: 100,
    percentage: 78,
    grade: 'C',
    rank: 4,
  },
  {
    student_id: 'std-5',
    student_name: 'Malika Umarova',
    avatar_url: null,
    score: 68,
    maximum_score: 100,
    percentage: 68,
    grade: 'D',
    rank: 5,
  },
]

// Mock Payments
export const MOCK_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-1',
    organization_id: 'org-ilmziyo',
    student_id: 'std-1',
    amount: 650000,
    amount_in_tiyin: 65000000,
    payment_date: '2026-09-02',
    due_date: '2026-09-05',
    status: 'PAID',
    method: 'CLICK',
    note: "Sentyabr oyi uchun oylik to'lov",
    receipt_number: 'KV-REC0901',
    transaction_id: 'TX-CLICK9012',
    created_at: '2026-09-02T11:20:00Z',
    updated_at: '2026-09-02T11:20:00Z',
    student: {
      id: 'std-1',
      first_name: 'Jamshid',
      last_name: 'Rasulov',
      phone: '+998 90 123 45 67',
      group_name: 'Matematika Intensive (G-12)',
      group_subject: 'Matematika',
    },
  },
  {
    id: 'pay-2',
    organization_id: 'org-ilmziyo',
    student_id: 'std-2',
    amount: 800000,
    amount_in_tiyin: 80000000,
    payment_date: '2026-09-03',
    due_date: '2026-09-05',
    status: 'PAID',
    method: 'PAYME',
    note: "Payme orqali onlayn to'lov",
    receipt_number: 'KV-REC0902',
    transaction_id: 'TX-PAYME9023',
    created_at: '2026-09-03T15:45:00Z',
    updated_at: '2026-09-03T15:45:00Z',
    student: {
      id: 'std-2',
      first_name: 'Jasur',
      last_name: 'Alimov',
      phone: '+998 97 765 43 21',
      group_name: 'IELTS 7.5+ Masterclass',
      group_subject: 'Ingliz tili',
    },
  },
  {
    id: 'pay-3',
    organization_id: 'org-ilmziyo',
    student_id: 'std-3',
    amount: 950000,
    amount_in_tiyin: 95000000,
    payment_date: null,
    due_date: '2026-09-10',
    status: 'OVERDUE',
    method: 'CASH',
    note: 'Muddat 1 kun kechikkan',
    receipt_number: 'KV-REC0903',
    transaction_id: 'TX-PEND9034',
    created_at: '2026-09-01T09:00:00Z',
    updated_at: '2026-09-01T09:00:00Z',
    student: {
      id: 'std-3',
      first_name: 'Madina',
      last_name: 'Karimova',
      phone: '+998 99 888 77 66',
      group_name: 'Frontend React & Next.js',
      group_subject: 'Dasturlash',
    },
  },
  {
    id: 'pay-4',
    organization_id: 'org-ilmziyo',
    student_id: 'std-4',
    amount: 550000,
    amount_in_tiyin: 55000000,
    payment_date: '2026-09-05',
    due_date: '2026-09-05',
    status: 'PAID',
    method: 'CASH',
    note: 'Kassaga naqd topshirildi',
    receipt_number: 'KV-REC0904',
    transaction_id: 'TX-CASH9045',
    created_at: '2026-09-05T14:10:00Z',
    updated_at: '2026-09-05T14:10:00Z',
    student: {
      id: 'std-4',
      first_name: 'Behruz',
      last_name: 'Saidov',
      phone: '+998 91 234 56 78',
      group_name: 'Fizika Olimpiada Guruhi',
      group_subject: 'Fizika',
    },
  },
]

// Mock Debtors
export const MOCK_DEBTORS: DebtSummary[] = [
  {
    student_id: 'std-3',
    student_name: 'Madina Karimova',
    phone: '+998 99 888 77 66',
    group_name: 'Frontend React & Next.js',
    pending_amount: 950000,
    overdue_amount: 950000,
    total_debt: 950000,
    last_payment_date: '2026-08-10',
    days_overdue: 2,
    status: 'OVERDUE',
  },
]

// Mock Finance Stats
export const MOCK_FINANCE_STATS: FinanceStats = {
  total_collected_month: 28000000,
  pending_amount: 3200000,
  overdue_debtors_count: 1,
  total_transactions_count: 48,
  payment_methods_breakdown: {
    CLICK: 12500000,
    PAYME: 9500000,
    CASH: 5000000,
    UZUM: 1000000,
  },
  monthly_trend: [
    { month: 'Apr 2026', amount: 19500000, count: 32 },
    { month: 'May 2026', amount: 22000000, count: 38 },
    { month: 'Iyun 2026', amount: 24500000, count: 42 },
    { month: 'Iyul 2026', amount: 26000000, count: 44 },
    { month: 'Avg 2026', amount: 27500000, count: 46 },
    { month: 'Sen 2026', amount: 28000000, count: 48 },
  ],
}

// Mock Teachers
export const MOCK_TEACHERS: TeacherListItem[] = [
  {
    id: 'tch-1',
    first_name: 'Anvar',
    last_name: 'Qodirov',
    phone: '+998 90 111 22 33',
    email: 'anvar@ilmziyo.uz',
    avatar_url: null,
    specialization: 'Oliy Matematika',
    status: 'ACTIVE',
    created_at: '2026-01-10T08:00:00Z',
    updated_at: '2026-01-10T08:00:00Z',
    is_deleted: false,
    groups_count: 2,
  },
  {
    id: 'tch-2',
    first_name: 'Lola',
    last_name: 'Karimova',
    phone: '+998 97 222 33 44',
    email: 'lola@ilmziyo.uz',
    avatar_url: null,
    specialization: 'IELTS & CEFR C1',
    status: 'ACTIVE',
    created_at: '2026-02-15T09:00:00Z',
    updated_at: '2026-02-15T09:00:00Z',
    is_deleted: false,
    groups_count: 1,
  },
  {
    id: 'tch-3',
    first_name: 'Javohirbek',
    last_name: 'Asqarov',
    phone: '+998 90 777 00 11',
    email: 'javohir@ilmziyo.uz',
    avatar_url: null,
    specialization: 'Senior Full-Stack & AI',
    status: 'ACTIVE',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
    is_deleted: false,
    groups_count: 1,
  },
]

// Mock Parents
export const MOCK_PARENTS: ParentListItem[] = [
  {
    id: 'prn-1',
    first_name: 'Dilshod',
    last_name: 'Rasulov',
    phone: '+998 90 999 11 22',
    email: null,
    notification_enabled: true,
    telegram_verified: true,
    telegram_username: '@dilshod_r',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-20T10:00:00Z',
    is_deleted: false,
    child_count: 1,
  },
  {
    id: 'prn-2',
    first_name: 'Nilufar',
    last_name: 'Alimova',
    phone: '+998 93 555 44 33',
    email: null,
    notification_enabled: true,
    telegram_verified: true,
    telegram_username: '@nilufar_alimova',
    created_at: '2026-08-19T14:30:00Z',
    updated_at: '2026-08-19T14:30:00Z',
    is_deleted: false,
    child_count: 1,
  },
]
